### ISSUE TITLE
New release + Version in the README?

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/SpellRevisions#104]
(1) Could a new release be published on github?
(2) Could the main README mention that version too?

It would be quite useful for people who try to gather
different mods. Hopefully one day I can use a ruby
script to download all of that, batch install via
weidu automatically and make this then available
to other folks.

Also it would be nice if we could have documentation
on github as-is; external website is nice, but I'd
prefer reading this all contained in github. A simple
.md file is enough. I had a look at the .md files in
this mod but these were very short so I probably
looked at the wrong file...

**Comment by lambda-dom** [comment]
New release out. Could you be more explicit about what you want to see in the docs? The top readme contains links to them -- the docs themselves are a tad outdated, and updating is something I have to look into as there are some semi-automated generation steps involved.

**Comment by lambda-dom** [comment]
Closing this, as it was for an older version and no followup on the info request-
