### ISSUE TITLE
Imprisonment: Character dies after being freed

### ISSUE THREAD

**Issue by FeuerTiger86** [Gibberlings3/SpellRevisions#109]
I have the following problem: When a character is imprisoned, he gets the Maze icon and he dies after a few rounds, which is the correct behaviour with this mod, I believe. However, he also dies if Freedom is cast in time, which is particularly annoying if it is the main character. I'm using v4 Beta 18.

**Comment by lambda-dom** [comment]
This definitely should *not* happen. Would you be so kind and attach your weidu.log and the file spwi910.spl. Also, how did you free the character, via a scroll, cast the freedom spell, what?

**Comment by FeuerTiger86** [comment]
It's the same with scroll and spell.

[WeiDU.log](https://github.com/Gibberlings3/SpellRevisions/files/10202828/WeiDU.log)
[spwi910.zip](https://github.com/Gibberlings3/SpellRevisions/files/10202842/spwi910.zip)

**Comment by lambda-dom** [comment]
Do not see anything obviously wrong with the log or the spell -- the spell state opcode is *different* than what it should be but I think that has no effect. Could you provide the freedom spell as well please, e.g. spwi917.spl?

I hate the imprisonment spell.

**Comment by FeuerTiger86** [comment]
I already finished Throne of Bhaal and uninstalled the game because I had a number of issues that were possibly caused by mods.

I quickly re-installed it and only installed Spell Revisions, and the same thing happened.

Thank you, anyway.

**Comment by lambda-dom** [comment]
Closing this, as I finally understand what is going on (in hindsight it was obvious). Patch incoming.
