### ISSUE TITLE
Lightning bolt w/ wrong damage

### ISSUE THREAD

**Issue by ChitownWillie** [Gibberlings3/SpellRevisions#123]
For SPCL722.SPL, Description reads:

"Upon casting this spell, the wizard releases a powerful stroke of electrical energy that inflicts 1d6 points of damage per level of the spellcaster (maximum damage of 10d6) to the target creature. A successful saving throw vs. breath at -4 reduces this damage to half."

But behind-the-scenes, the two (2) Damage Effects are:

![image](https://github.com/Gibberlings3/SpellRevisions/assets/65503897/409611a2-33f0-41e3-848d-6524a1ef37c8)

And

![image](https://github.com/Gibberlings3/SpellRevisions/assets/65503897/e1391f68-251d-4581-8275-7662d4bfec61)

Confirmed in game with my Priest of Talos:

![image](https://github.com/Gibberlings3/SpellRevisions/assets/65503897/0c49600c-9738-4209-8746-68ce7a0f31af)

Installed:

00000: /* created or unbiffed */ SPELL_REV/SETUP-SPELL_REV.TP2 0 0 // Spell Revisionsv4.19

**Comment by lambda-dom** [comment]
This is the Talos cleric kit version of lightning bolt, if I am not mistaken.  So the fix is d8 -> d6, correct? Submitting a patch soon.

**Comment by ChitownWillie** [comment]
Problem is that a level 1 Priest of Talos is still doing 3D8 + 2D8 - when
it should be 1D6.

**Comment by ChitownWillie** [comment]
See also:

https://forums.beamdog.com/discussion/38492/priest-of-talos-lightning-bolt-should-cause-the-appropriate-damage-at-levels-1-through-4

**Comment by lambda-dom** [comment]
The die and the save penalty is already in the patch, so it is missing the 1-4 level headers (and re-level the first header). Fixing it soon-ish.

**Comment by ChitownWillie** [comment]
Thank you!

**Comment by lambda-dom** [comment]
Closing the issue as the patch is in.

**Comment by ChitownWillie** [comment]
Thanks again! Is the patch available as a standalone? I'd like to apply to
an existing installation.

**Comment by lambda-dom** [comment]
The only thing the patch corrects, gamewise, is the spell itself. So if you want to apply it to a running installation, click the code button in the front page to download the latest snapshot, pluck out `spcl722.spl` from the `spell_rev/shared` folder and drop it on the override folder of the bg installation.
