### ISSUE TITLE
Sleep does not work at all with 4.19rc4 on MacOS BG:EE

### ISSUE THREAD

**Issue by luc-j-bourhis** [Gibberlings3/SpellRevisions#128]
Casting the spell does absolutely nothing. The game shows "X unconscious" but the target does not even drop on the floor. It just continues to fight me as if no spell had been cast. Is that related to TobEx not being available on MacOS? I thought that BG:EE implemented enough of it.

**Comment by luc-j-bourhis** [comment]
For good measure, I tried on Windows as well. Install of Spell Revision on a fresh install of BG:EE. No other mod. Sleep is broken as well: the target falls asleep and wakes up within a second. So it seems that BG:EE is the culprit here. I installed the latest version on GOG at the time of writing this: v2.6.6.0. I attached Weidu.log 
[WeiDU.log](https://github.com/Gibberlings3/SpellRevisions/files/13654286/WeiDU.log)

**Comment by subtledoctor** [comment]
Install [this hotfix](https://github.com/subtledoctor/SubtleD_hotfixes/releases/tag/v27).

**Comment by luc-j-bourhis** [comment]
It works! Thank you so much. So now can I install SCS? Or should your fix be installed after SCS?

**Comment by lambda-dom** [comment]
Patch submitted and applied. If issue persists, re-open it.
