### ISSUE TITLE
The game crashed when I cast Magic Fang (SR) on my minions.

### ISSUE THREAD

**Issue by AnOpenHeresy** [Gibberlings3/SpellRevisions#130]
[WeiDU.log](https://github.com/Gibberlings3/SpellRevisions/files/14515263/WeiDU.log)
[dump.2.6.6.0.0018.zip](https://github.com/Gibberlings3/SpellRevisions/files/14515264/dump.2.6.6.0.0018.zip)
[debug123.txt](https://github.com/Gibberlings3/SpellRevisions/files/14515269/debug123.txt)
Bubb13 said that "One of your mods applied an op232 with param2 = 10 and special = 0. This results in a divide by zero and crashes the game. "
and
[sppr327.spl-WeiDU-FileChangelog-2024-Mar-06.txt](https://github.com/Gibberlings3/SpellRevisions/files/14515643/sppr327.spl-WeiDU-FileChangelog-2024-Mar-06.txt)
The game crashes when I use the spell on bats...

**Comment by lambda-dom** [comment]
Patch submitted and applied. Closing the issue.
