### ISSUE TITLE
Divine find traps broken v4.19rc1 Windows

### ISSUE THREAD

**Issue by SandwichM4n** [Gibberlings3/SpellRevisions#135]
Find traps in cleric spell list seems to be broken. On cast it doesn't reveal any traps, nor it does with per round ticks. Tested it at the same exact trap in vanilla and it works there. 
Sometimes this spell also causes the "invalid 74011" error in dialogue log, although i can't recreate it constantly.

**Comment by lambda-dom** [comment]
Can confirm that the spell does not work, but not the "invalid 74011" error. Looking into it.

**Comment by lambda-dom** [comment]
Found the problem. If you want to test the solution, install the attached mod -- it just drops fixed copies of the relevant spells in override. Can be installed in a running game. The mod is zipped, so unzip it first.
[sr_find_traps_fix.zip](https://github.com/Gibberlings3/SpellRevisions/files/14812704/sr_find_traps_fix.zip)

**Comment by lambda-dom** [comment]
Patch submitted and applied. Waiting for the OP to answer and then closing the issue.

**Comment by lambda-dom** [comment]
No news from the OP, so closing the issue as resolved. Re-open if needed.
