### ISSUE TITLE
Want to remove the Slow Effect From Flesh to Stone

### ISSUE THREAD

**Issue by WeareTheDraiken** [Gibberlings3/SpellRevisions#136]
Hello

Currently playing with Spell Revision bus somthing that always bothers me is that when I  do /* within the main component to not install flesh to stone , it still installs the spwi604d and eff files.

Anyway I installed another mod that revamps Petrification state but I dislike that slow effect of Flesh to Stone that persists even though I remove spwi604 and spwi604eff manually.

So I'm requesting just to be told what is the actual file in the override that is responsible for that slow effect that is attached to flesh to stone , so I can finally remove it manually because I find it heavily annoying, I just want my Petrification to be straigh up without that thing.

**Comment by lambda-dom** [comment]
Closing the issue, then.

**Comment by WeareTheDraiken** [comment]
Yeah that's fine.
