### ISSUE TITLE
Request: Animal Growth/Some Individuals Mod Compatibility

### ISSUE THREAD

**Issue by Endarire** [Gibberlings3/SpellRevisions#82]
Greetings, all!

[Some Individuals](https://www.gibberlings3.net/forums/topic/31405-some-individuals-mod-for-soatutu-or-possibly-only-for-ee/) offers color variations for a variety of creatures including animals.  May we get _animal growth_ to produce the appropriate colored versions of creatures with Some Individuals installed?

Thankee!

**Comment by lambda-dom** [comment]
I am not sure what exactly are you requesting as the spell itself, in graphical terms, only applies a color pulse and an over-the-creature animation. At any rate, this is definitely *not* within the scope of the mod.
