### ISSUE TITLE
Spell Shield not removed after a spell attack

### ISSUE THREAD

**Issue by kelthalas** [Gibberlings3/SpellRevisions#9]
Hey

The level 5 Spell Shield wich protects the caster from a single spell attack is not removed after absobing it, effectively protecting the caster against all spell attacks for the whole duration

I noticed this while doing the wiazrd duel in the drow city, as I couldn't remove it no matter how many secret words and pierce magic I threw at him.

I tested it with a simulacrum casting secret word,/pierce magic on my protected mage, I get "Spell Ineffective" but the Spell Shield buff remains. With spell shield, my protections are correctly dispelled

weidu log just in case http://pastebin.com/jwu2hJ04
Thanks

**Comment by kelthalas** [comment]
Nevermind, the bug is caused by Refinement which ovewrites the file (which is weird because it's not HLA related...)

**Comment by mike1072** [comment]
Thanks for looking into it.
